# Exported from:        http://host.docker.internal:5516/
# Release version:      23.1.2
# Date created:         Mon Jun 19 09:02:40 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
  - Permissions.yaml
